# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'New_map_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for New_map_app

  target 'New_map_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'New_map_appUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'lottie-ios'

pod 'paper-onboarding', '~> 2.0.1'
end
